#!/bin/bash
###########################################################################
#                    <>       rclone_cleanup       <>                     #
###########################################################################
#
####################  Check if script already running  ####################
#
sleep 1
echo "$(date "+%d.%m.%Y %T") INFO: *********************       Starting rclone_cleanup script       *********************"
echo "$(date "+%d.%m.%Y %T") INFO: *** Starting rclone_cleanup script ***"
if [[ -f "/mnt/user/appdata/other/rclone/rclone_cleanup_running" ]]; then
echo "$(date "+%d.%m.%Y %T") INFO: Exiting as is script already running."
exit
else
touch /mnt/user/appdata/other/rclone/rclone_cleanup_running
fi
####################      Clean-up UnionFS Folder      ####################
#
echo "$(date "+%d.%m.%Y %T") INFO: starting unionfs cleanup."
find /mnt/user/g/drive/.unionfs -name '*_HIDDEN~' | while read line; do
oldPath=${line#/mnt/user/g/drive/.unionfs}
newPath=/mnt/user/mount_rclone/g${oldPath%_HIDDEN~}
rm "$newPath"
rm "$line"
done
find "/mnt/user/g/drive/.unionfs" -mindepth 1 -type d -empty -delete
rm /mnt/user/appdata/other/rclone/rclone_cleanup_running
echo "$(date "+%d.%m.%Y %T") INFO: ********************* rclone_cleanup script finished successfully *********************"
exit